[package]
name = "explain-stm32"
version = "0.1.0"
authors = ["Thomas Gravekamp <thomas.gravekamp@fontoxml.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
